### ISSUE TITLE
Trouble configuring Grafana

### ISSUE THREAD

**Issue by jeff47** [knightjoel/solaredge_monitoring#1]
Thanks for this great guide -- but I'm having a little trouble getting it working, probably due to changes in software versions since it was written.

Everything seems to be OK until I get to the Configure Grafana section.  In Grafana v9.0.2, when adding the data source and selecting Flux, there is no place to put in a database.  The options are organization, token and bucket now.

Any suggestions on how to proceed?  This is the first time I've used influxdb.

**Comment by jeff47** [comment]
I think I got it working - it's a bit quirky how the bucket<->database language is used.  Have you updated influx to v2 or still on 1.8?

**Comment by knightjoel** [comment]
Still on 1.8. This system is installed at a remote site so I likely will never update it.
