### ISSUE TITLE
solarEdgeCloudScraper.py KeyError: 'temperature'

### ISSUE THREAD

**Issue by jeff47** [knightjoel/solaredge_monitoring#2]
When trying to import the historical data, I ran into this error.  I can't tell exactly the cause -- is this an authentication error with the cloud, or something different?

```root@85a36b9078e1:/# telegraf --once --config /etc/telegraf/telegraf-onetime-solaredge-history.conf
2022-08-15T02:33:19Z I! Starting Telegraf 1.23.3
2022-08-15T02:33:19Z I! Loaded inputs: exec
2022-08-15T02:33:19Z I! Loaded aggregators: 
2022-08-15T02:33:19Z I! Loaded processors: 
2022-08-15T02:33:19Z I! Loaded outputs: influxdb
2022-08-15T02:33:19Z I! Tags enabled: 
2022-08-15T02:33:19Z D! [agent] Initializing plugins
2022-08-15T02:33:19Z D! [agent] Connecting outputs
2022-08-15T02:33:19Z D! [agent] Attempting connection to [outputs.influxdb]
2022-08-15T02:33:19Z D! [agent] Successfully connected to outputs.influxdb
2022-08-15T02:33:19Z D! [agent] Starting service inputs
2022-08-15T02:33:25Z E! [inputs.exec] Error in plugin: exec: exit status 1 for command '/etc/telegraf/solarEdgeCloudScraper.py history': Traceback (most recent call last):
  File "/etc/telegraf/solarEdgeCloudScraper.py", line 557, in <module>
    scrape_full_history()
  File "/etc/telegraf/solarEdgeCloudScraper.py", line 531, in scrape_full_history
    while not get_data_api(site, week[0], week[1]):
  File "/etc/telegraf/solarEdgeCloudScraper.py", line 394, in get_data_api
    f'data,site={site},sn={serial} I_Temp={value["temperature"]},I_AC_Energy_WH={value["totalEnergy"]},I_AC_Power={value["totalActivePower"]}{conditionalData} {to_unix_timestamp(date)}',
KeyError: 'temperature'
2022-08-15T02:33:25Z D! [agent] Stopping service inputs
2022-08-15T02:33:25Z D! [agent] Input channel closed
2022-08-15T02:33:25Z I! [agent] Hang on, flushing any cached metrics before shutdown
2022-08-15T02:33:25Z D! [outputs.influxdb] Buffer fullness: 0 / 1000000 metrics
2022-08-15T02:33:25Z I! [agent] Stopping running outputs
2022-08-15T02:33:25Z D! [agent] Stopped Successfully
2022-08-15T02:33:25Z E! [telegraf] Error running agent: input plugins recorded 1 errors```

**Comment by knightjoel** [comment]
Hey Jeff,

That error indicates something amiss with the data returned from the SolarEdge API.

Could you pull down this [modified version of the scraper](https://github.com/knightjoel/solaredge_monitoring/blob/issues/2/telegraf/solarEdgeCloudScraper.py) to help debug?

1. Pull down the modified solarEdgeCloudScraper.py
2. Edit it with your API key, username, and password
3. Run it from the CLI (not via telegraph) with `python3 solarEdgeCloudScraper.py debug`
4. Share the output from  step 3 here.

Please check the output before you share it for any sensitive information; I don't remember what kind of potentially sensitive information might be there.

**Comment by jeff47** [comment]
> That error indicates something amiss with the data returned from the SolarEdge API.

Will do.  It produced a lot more output than I expected and when I ran it again to redirect to a debug file, I think I hit the API call limit (?).  So I will try again tomorrow I guess.  Is there a way to run this so that it only uses the API vs scrapes, to test those components individually?

This is the output I was able to save, but as I said I think it might be only the scrape not the API:
[debug.txt](https://github.com/knightjoel/solaredge_monitoring/files/9338186/debug.txt)

**Comment by jeff47** [comment]
Could the issue be that my system isn't producing yet, so the history values might be null?  The inverters are connected are reporting status through the website and Modbus, but they are in standby so my energy production is zero.  Still waiting on the inspection.

**Comment by knightjoel** [comment]
> Will do. It produced a lot more output than I expected and when I ran it again to redirect to a debug file, I think I hit the API call limit (?). So I will try again tomorrow I guess. Is there a way to run this so that it only uses the API vs scrapes, to test those components individually?

Yes, please grab https://github.com/knightjoel/solaredge_monitoring/blob/issues/2/telegraf/solarEdgeCloudScraper.py again. I've commented out everything except the data API poller bits.

> Could the issue be that my system isn't producing yet, so the history values might be null? The inverters are connected are reporting status through the website and Modbus, but they are in standby so my energy production is zero. Still waiting on the inspection.

Hmm, could be. I didn't have this software running while the system was being commissioned so I don't know what kind of data the API returns/doesn't return in that case. If you find that is what's going on, I'd gladly update the documentation here so others don't get tripped up.

**Comment by jeff47** [comment]
It works!  The original solarEdgeCloudScraper.py (the one that includes the I_Temp on line 394) appears to produce no API output.  The refactored one (pprint on line 393) produces the output attached here.

[solaredge_data.txt](https://github.com/knightjoel/solaredge_monitoring/files/9352397/solaredge_data.txt)

One issue I had was that I didn't realize that the `lastupdated` file short-circuited subsequent runs, so that was interfering with troubleshooting.  Maybe when `debug` is specified, that file should be ignored....?

Regarding the first version of solarEdgeCloudScraper.py.  It seemed like the temperature call was the one with a problem, however it does appear to have that key.  See below:
```
>>> r = requests.get(f"https://monitoringapi.solaredge.com/equipment/3051962/XXXXXCF/data", {'startTime': "2022-08-14 01:01:01", 'endTime': "2022-08-16 01:01:01", 'api_key': "XXXX"})
>>>r.json()['data']['telemetries']
[{'date': '2022-08-14 01:02:13', 'totalActivePower': 0.0, 'dcVoltage': 0.178426, 'powerLimit': 100.0, 'totalEnergy': 656.0, 'temperature': 30.7678, 'inverterMode': 'LOCKED_STANDBY', 'operationMode': 0, 'vL1ToN': 128.746, 'vL2ToN': 129.049, 'L1Data': {'acCurrent': 0.0, 'acVoltage': 257.795, 'acFrequency': 59.9525, 'apparentPower': 0.0, 'activePower': 0.0, 'reactivePower': 0.0, 'cosPhi': 0.0}},...,{'date': '2022-08-16 00:57:13', 'totalActivePower': 0.0, 'dcVoltage': None, 'powerLimit': 100.0, 'totalEnergy': 656.0, 'temperature': 28.8692, 'inverterMode': 'LOCKED_STANDBY', 'operationMode': 0, 'vL1ToN': 129.623, 'vL2ToN': 129.519, 'L1Data': {'acCurrent': 0.0, 'acVoltage': 259.142, 'acFrequency': 60.0155, 'apparentPower': 0.0, 'activePower': 0.0, 'reactivePower': 0.0, 'cosPhi': 0.0}}
```

**Comment by jeff47** [comment]
OK, while this works when running `debug`, it still throws an error when running `history`:

```
2022-08-16T17:25:55Z I! Starting Telegraf 1.23.3
2022-08-16T17:25:55Z I! Loaded inputs: exec
2022-08-16T17:25:55Z I! Loaded aggregators: 
2022-08-16T17:25:55Z I! Loaded processors: 
2022-08-16T17:25:55Z I! Loaded outputs: influxdb_v2
2022-08-16T17:25:55Z I! Tags enabled: 
2022-08-16T17:25:55Z D! [agent] Initializing plugins
2022-08-16T17:25:55Z D! [agent] Connecting outputs
2022-08-16T17:25:55Z D! [agent] Attempting connection to [outputs.influxdb_v2]
2022-08-16T17:25:55Z D! [agent] Successfully connected to outputs.influxdb_v2
2022-08-16T17:25:55Z D! [agent] Starting service inputs
2022-08-16T17:26:05Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 100000 metrics
2022-08-16T17:26:06Z E! [inputs.exec] Error in plugin: metric parse error: expected field at 1821:25: "{'L1Data': {'acCurrent': 0.0,"
2022-08-16T17:26:06Z D! [agent] Stopping service inputs
2022-08-16T17:26:06Z D! [agent] Input channel closed
2022-08-16T17:26:06Z I! [agent] Hang on, flushing any cached metrics before shutdown
2022-08-16T17:26:06Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 100000 metrics
2022-08-16T17:26:06Z I! [agent] Stopping running outputs
2022-08-16T17:26:06Z D! [agent] Stopped Successfully
2022-08-16T17:26:06Z E! [telegraf] Error running agent: input plugins recorded 1 errors
```

**Comment by jeff47** [comment]
Here's the output from `python3 solarEdgeCloudScraper.py history`.

[history.txt](https://github.com/knightjoel/solaredge_monitoring/files/9353334/history.txt)

**Comment by jeff47** [comment]
OK, I was able to fix this error with some value checking just before the print(f'data...) statement on line 392:

```
             if not 'temperature' in value:
                 value["temperature"] = ""
             if not 'totalEnergy' in value:
                 value["totalEnergy"] = ""
             if not 'totalActivePower' in value:
                 value["totalActivePower"] = ""
```
I don't know how often those fields are missing -- perhaps very rarely?  And if there are additional data fields that should also be checked.

**Comment by knightjoel** [comment]
> Thanks for your patience while I fuss with this. 

Thanks a lot for collaborating on the troubleshooting and not just lobbing it over the fence :-)

> It appears that the API is returning incomplete data for some timepoints:
> 
> I added a `print(value)` line just before it tries to format into a influx line format, and here's the tail:
> 
> ```
> {'date': '2022-08-10 09:28:52', 'totalActivePower': 0.0, 'dcVoltage': 13.3242, 'powerLimit': 100.0, 'totalEnergy': 37.0, 'temperature': 34.4801, 'inverterMode': 'LOCKED_STANDBY', 'operationMode': 0, 'vL1ToN': 124.617, 'vL2ToN': 124.298, 'L1Data': {'acCurrent': 0.0, 'acVoltage': 248.915, 'acFrequency': 60.0153, 'apparentPower': 0.0, 'activePower': 0.0, 'reactivePower': 0.0, 'cosPhi': 0.0}}
> data,site=3051962,sn=730E907B-8C I_Temp=34.4801,I_AC_Energy_WH=37.0,I_AC_Power=0.0,I_DC_Voltage=13.3242,I_L1_AC_Voltage=248.915,I_L1_AC_Current=0.0,I_L1_AC_PF=0.0,I_L1_AC_Freq=60.0153,I_L1_AC_VAR=0.0,I_L1_AC_VA=0.0,I_L1_AC_Power=0.0 1660138132000000000
> {'date': '2022-08-10 09:33:52', 'totalActivePower': 0.0, 'dcVoltage': 13.1364, 'powerLimit': 100.0, 'totalEnergy': 37.0, 'inverterMode': 'LOCKED_STANDBY', 'operationMode': 0, 'vL1ToN': 124.486, 'vL2ToN': 124.522, 'L1Data': {'acCurrent': 0.0, 'acVoltage': 249.008, 'acFrequency': 60.0054, 'apparentPower': 0.0, 'activePower': 0.0, 'reactivePower': 0.0, 'cosPhi': 0.0}}
> ```
> 
> The last line is just before it hit an error and died: it's missing the temperature field. I guess some error checking is needed for missing values to prevent this. Is there a way to just insert a null value if it's missing?

Nice catch. That's the data I was looking to capture.

I'm reluctant to insert nulls or zeros because that will mess with the trends shown in Grafana. My preference would be to throw away the whole response rather than fill it in with arbitrary data. I've added a bunch of try/except guards around the code that processes the response from the API. This will make it more robust and even catch more cases of bad data than what you're experiencing. Could you [give it a try](https://github.com/knightjoel/solaredge_monitoring/blob/53ffbcf863b60e7b87e2f8fa1567abec315a0d26/telegraf/solarEdgeCloudScraper.py)?

**Comment by jeff47** [comment]
> I'm reluctant to insert nulls or zeros because that will mess with the trends shown in Grafana. My preference would be to throw away the whole response rather than fill it in with arbitrary data. I've added a bunch of try/except guards around the code that processes the response from the API. This will make it more robust and even catch more cases of bad data than what you're experiencing. Could you [give it a try](https://github.com/knightjoel/solaredge_monitoring/blob/53ffbcf863b60e7b87e2f8fa1567abec315a0d26/telegraf/solarEdgeCloudScraper.py)?

Looks good!
