### ISSUE TITLE
data from cloud

### ISSUE THREAD

**Issue by frezeen** [knightjoel/solaredge_monitoring#4]
hi, i have all up and running but when i launch hystory script ill grab data from my first installation day to 2 july 2022.
i miss all data from 2 july 2022 to today.

![image](https://github.com/knightjoel/solaredge_monitoring/assets/38480611/82bddf39-325c-4e00-8701-4838b63e7c52)

i can see this data in influxdb explorer

**Comment by knightjoel** [comment]
I apologize, but I'm unable to offer support on this project. I'm making it available so others can build off of it.
